py:
	python solution.py

r:
	Rscript solution.R

cpp:
	g++ solution.cpp -o solution && ./solution

c:
	gcc solution.c -o solution && ./solution

java:
	javac solution.java && java solution

js:
	node solution.js

ts:
	npx ts-node solution.ts

v:
	v run solution.v

sh:
	bash solution.sh